version: '3.8'

services:
  musicgen-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./generated_audio:/app/generated_audio
    environment:
      - PYTORCH_ENABLE_MPS_FALLBACK=1
    restart: unless-stopped
